# Generated by Django 5.0.1 on 2024-03-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_imuser_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="imuser",
            name="is_blocked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="imuser",
            name="permanant_login_fail",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="imuser",
            name="temporal_login_fail",
            field=models.IntegerField(default=1),
        ),
    ]
