# Generated by Django 5.0.1 on 2024-03-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_imuser_is_blocked_imuser_permanant_login_fail_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imuser",
            name="permanant_login_fail",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="imuser",
            name="temporal_login_fail",
            field=models.IntegerField(default=0),
        ),
    ]
