# Generated by Django 5.0.1 on 2024-03-04 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_imuser_permanant_login_fail_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="imuser", name="permanant_login_fail",),
        migrations.RemoveField(model_name="imuser", name="temporal_login_fail",),
    ]
