# Generated by Django 5.0.1 on 2024-02-12 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_classattendance"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResolutionStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resolution_status", models.CharField(max_length=225, unique=True)),
            ],
        ),
    ]
