# Generated by Django 5.0.1 on 2024-03-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_query_query_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="query",
            name="query_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FACILITY", "Facility"),
                    ("LOGISTICS", "Logistics"),
                    ("KITCHEN", "Kitchen"),
                ],
                default="FACILITY",
                max_length=50,
                null=True,
            ),
        ),
    ]
